---
- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Sysctl configuration
  template:
    src: "99-kubernetes.conf"
    dest: "/etc/99-kubernetes.conf"

- shell: sysctl -p

- name: Add Kubernetes APT key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Configure ip forward
  shell: echo "1" > /proc/sys/net/ipv4/ip_forward

- name: Add Kubernetes APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: "kubernetes"

- name: Install Kubernetes packages
  apt:
    pkg:
      - "kubectl={{ kubernetes_version }}"
      - "kubeadm={{ kubernetes_version }}"
      - "kubelet={{ kubernetes_version }}"
    update_cache: yes
    state: present

- name: Hold kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubectl
    - kubeadm
    - kubelet

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
