# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "bento/ubuntu-20.04"


# Insert public key if one found in this directory
ssh_pub_key = ''
if File.file?('id_rsa.pub')
   ssh_pub_key = File.readlines('id_rsa.pub').first.strip
end

provisionner=<<-SHELL

    set -x

    # Update system
    apt-get update && apt-get upgrade -y

    # Install helpers
    apt-get install -y vim net-tools sed curl wget byobu ranger

    # Change default passwords
    echo 'root:azerty' | chpasswd
    echo 'ubuntu:azerty' | chpasswd

    # Configure SSH
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

    sed -i -E 's/#?PermitRootLogin.+/PermitRootLogin yes/g' /etc/ssh/sshd_config
    sed -i -E 's/#?PasswordAuthentication.+/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sed -i -E 's/#?UsePAM.+/UsePAM no/g' /etc/ssh/sshd_config

    systemctl restart ssh

    # Copy SSH key
    echo "#{ssh_pub_key}" >> /root/.ssh/authorized_keys

    # Show interfaces
    ip a

SHELL

Vagrant.configure("2") do |config|
  hostname = "single-node-vm0"

  config.vm.box = box
  config.vm.provider "virtualbox"
  config.vm.hostname = hostname
  config.vm.provision :shell, inline: provisionner
  config.vm.network :private_network, ip: "192.168.56.50",  auto_config: true

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.name = hostname
  end
end
